import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import Link from 'next/link';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'My First Next.js App 🤓',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body className='bg-purple-50'>
        <div className='relative isolate flex items-center justify-center gap-x-6 overflow-hidden bg-gray-50 px-6 py-2.5 sm:px-3.5'>
          <div
            className='absolute left-[max(-7rem,calc(50%-52rem))] top-1/2 -z-10 -translate-y-1/2 transform-gpu blur-2xl'
            aria-hidden='true'
          >
            <div
              className='aspect-[577/310] w-[36.0625rem] bg-gradient-to-r from-[#ff80b5] to-[#9089fc] opacity-30'
              style={{
                clipPath:
                  'polygon(74.8% 41.9%, 97.2% 73.2%, 100% 34.9%, 92.5% 0.4%, 87.5% 0%, 75% 28.6%, 58.5% 54.6%, 50.1% 56.8%, 46.9% 44%, 48.3% 17.4%, 24.7% 53.9%, 0% 27.9%, 11.9% 74.2%, 24.9% 54.1%, 68.6% 100%, 74.8% 41.9%)',
              }}
            />
          </div>
          <div
            className='absolute left-[max(45rem,calc(50%+8rem))] top-1/2 -z-10 -translate-y-1/2 transform-gpu blur-2xl'
            aria-hidden='true'
          >
            <div
              className='aspect-[577/310] w-[36.0625rem] bg-gradient-to-r from-[#ff80b5] to-[#9089fc] opacity-30'
              style={{
                clipPath:
                  'polygon(74.8% 41.9%, 97.2% 73.2%, 100% 34.9%, 92.5% 0.4%, 87.5% 0%, 75% 28.6%, 58.5% 54.6%, 50.1% 56.8%, 46.9% 44%, 48.3% 17.4%, 24.7% 53.9%, 0% 27.9%, 11.9% 74.2%, 24.9% 54.1%, 68.6% 100%, 74.8% 41.9%)',
              }}
            />
          </div>
          <div className='flex flex-wrap items-center gap-x-4 gap-y-2'>
            <strong className='font-semibold'>
              <Link href='/'>Home </Link>
            </strong>
            <svg viewBox='0 0 2 2' className='mx-2 inline h-0.5 w-0.5 fill-current' aria-hidden='true'>
              <circle cx={1} cy={1} r={1} />
            </svg>
            <strong className='font-semibold'>
              <Link href='/rendering/CSR'>CSR </Link>
            </strong>
            <svg viewBox='0 0 2 2' className='mx-2 inline h-0.5 w-0.5 fill-current' aria-hidden='true'>
              <circle cx={1} cy={1} r={1} />
            </svg>
            <strong className='font-semibold'>
              <Link href='/rendering/SSG'>SSG </Link>
            </strong>
            <svg viewBox='0 0 2 2' className='mx-2 inline h-0.5 w-0.5 fill-current' aria-hidden='true'>
              <circle cx={1} cy={1} r={1} />
            </svg>
            <strong className='font-semibold'>
              <Link href='/rendering/ISR'>ISR </Link>
            </strong>
            <svg viewBox='0 0 2 2' className='mx-2 inline h-0.5 w-0.5 fill-current' aria-hidden='true'>
              <circle cx={1} cy={1} r={1} />
            </svg>
            <strong className='font-semibold'>
              <Link href='/rendering/SSR'>SSR </Link>
            </strong>
          </div>
          <Link
            href='https://github.com/seopport'
            target='_blank'
            className='flex justify-self-end rounded-full bg-gray-900 px-3.5 py-1 text-sm font-semibold text-white shadow-sm hover:bg-gray-700 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-gray-900'
          >
            @seopport <span aria-hidden='true'></span>
          </Link>
        </div>{' '}
        <div className='flex flex-col justify-center items-center text-2xl font-light'>
          🤓 Next.js의 렌더링 기법을 이해해봅시다. 👽
        </div>
        {children}
      </body>
    </html>
  );
}
