import { Metadata } from 'next';
import React from 'react';

export const metadata: Metadata = {
  title: 'Understanding rendering 👽',
  description: 'Generated by create next app',
};

const renderingLayout = ({ children }: { children: React.ReactNode }) => {
  return <div>{children}</div>;
};

export default renderingLayout;
